In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [20]:
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
# from xgboost import XGBClassifier
from sklearn.neighbors import KNeighborsClassifier

In [22]:
df = pd.read_csv('DataSets/Ayurveda Sheet - Sheet2.csv')

In [24]:
df.head()

prognosis  Sneezing  Runny_Nose  Headache  High Fever  Bodyache  \
0   Allergy         1           1         0           0         0   
1   Allergy         1           1         0           0         0   
2   Allergy         1           1         0           0         0   
3   Allergy         1           1         0           0         0   
4   Allergy         1           1         0           0         0   

   Blocked_Nose  Tonsils  Throught_Iritation  Fatigue  ...  \
0             0        0                   0        0  ...   
1             0        0                   0        0  ...   
2             0        0                   0        0  ...   
3             0        0                   0        0  ...   
4             0        0                   0        0  ...   

   Increased Appetite  Sweating  Hair loss  Photosensitivity  Oral ulcers  \
0                   0       NaN          0                 0            0   
1                   0       NaN          0                 0            0   
2                   0       NaN          0                 0            0   
3                   0       NaN          0                 0            0   
4                   0       NaN          0                 0            0   

          Dosha  Risk  Risk for prognosis  \
0  Watha, Kapha  High                 NaN   
1  Watha, Kapha  High                 NaN   
2  Watha, Kapha  High                 NaN   
3  Watha, Kapha  High                 NaN   
4  Watha, Kapha  High                 NaN   

                                            Medicine  Unnamed: 78  
0  Turmeric and honey mixture, Ginger tea, Black ...          NaN  
1  Turmeric and honey mixture, Ginger tea, Black ...          NaN  
2  Turmeric and honey mixture, Ginger tea, Black ...          NaN  
3  Turmeric and honey mixture, Ginger tea, Black ...          NaN  
4  Turmeric and honey mixture, Ginger tea, Black ...          NaN  

[5 rows x 79 columns]

In [ ]:
df.tail()

In [ ]:
df.shape

In [ ]:
df.describe()

In [ ]:
df.info()

In [ ]:
df.isnull().sum()

In [28]:
# Remove S.No. column from data
df1 = df.drop(['Dosha','Risk for prognosis','Medicine', 'Unnamed: 78'], axis = 1)

In [30]:
df1.head()

prognosis  Sneezing  Runny_Nose  Headache  High Fever  Bodyache  \
0   Allergy         1           1         0           0         0   
1   Allergy         1           1         0           0         0   
2   Allergy         1           1         0           0         0   
3   Allergy         1           1         0           0         0   
4   Allergy         1           1         0           0         0   

   Blocked_Nose  Tonsils  Throught_Iritation  Fatigue  ...  Painful urination  \
0             0        0                   0        0  ...                  0   
1             0        0                   0        0  ...                  0   
2             0        0                   0        0  ...                  0   
3             0        0                   0        0  ...                  0   
4             0        0                   0        0  ...                  0   

   Frequent urge to urinate  Cloudy or strong-smelling urine  Pelvic pain  \
0                         0                                0            0   
1                         0                                0            0   
2                         0                                0            0   
3                         0                                0            0   
4                         0                                0            0   

   Increased Appetite  Sweating  Hair loss  Photosensitivity  Oral ulcers  \
0                   0       NaN          0                 0            0   
1                   0       NaN          0                 0            0   
2                   0       NaN          0                 0            0   
3                   0       NaN          0                 0            0   
4                   0       NaN          0                 0            0   

   Risk  
0  High  
1  High  
2  High  
3  High  
4  High  

[5 rows x 75 columns]

In [32]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 999 entries, 0 to 998
Data columns (total 75 columns):
 #   Column                           Non-Null Count  Dtype  
---  ------                           --------------  -----  
 0   prognosis                        999 non-null    object 
 1   Sneezing                         999 non-null    int64  
 2   Runny_Nose                       999 non-null    int64  
 3   Headache                         999 non-null    int64  
 4   High Fever                       999 non-null    int64  
 5   Bodyache                         999 non-null    int64  
 6   Blocked_Nose                     999 non-null    int64  
 7   Tonsils                          999 non-null    int64  
 8   Throught_Iritation               999 non-null    int64  
 9   Fatigue                          999 non-null    int64  
 10  Less_of_appetite                 999 non-null    int64  
 11  Eye Redness                      999 non-null    int64  
 12  Lethargy              

In [34]:
df2 = df1.copy()  # Create a copy of the original DataFrame
df2['Sweating'] = df2['Sweating'].fillna(0)

In [36]:
df2.isnull().sum()

prognosis           0
Sneezing            0
Runny_Nose          0
Headache            0
High Fever          0
                   ..
Sweating            0
Hair loss           0
Photosensitivity    0
Oral ulcers         0
Risk                0
Length: 75, dtype: int64

In [38]:
df2.nunique()

prognosis           20
Sneezing             2
Runny_Nose           2
Headache             2
High Fever           2
                    ..
Sweating             2
Hair loss            2
Photosensitivity     2
Oral ulcers          2
Risk                 4
Length: 75, dtype: int64

In [40]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 999 entries, 0 to 998
Data columns (total 75 columns):
 #   Column                           Non-Null Count  Dtype  
---  ------                           --------------  -----  
 0   prognosis                        999 non-null    object 
 1   Sneezing                         999 non-null    int64  
 2   Runny_Nose                       999 non-null    int64  
 3   Headache                         999 non-null    int64  
 4   High Fever                       999 non-null    int64  
 5   Bodyache                         999 non-null    int64  
 6   Blocked_Nose                     999 non-null    int64  
 7   Tonsils                          999 non-null    int64  
 8   Throught_Iritation               999 non-null    int64  
 9   Fatigue                          999 non-null    int64  
 10  Less_of_appetite                 999 non-null    int64  
 11  Eye Redness                      999 non-null    int64  
 12  Lethargy              

In [42]:
# Encode the 'Risk' and 'prognosis' columns
le = LabelEncoder()
df2['Risk'] = le.fit_transform(df2['Risk'])
df2['prognosis'] = le.fit_transform(df2['prognosis'])

In [44]:
X = df2.drop('Risk', axis=1)  # Features
y = df2['Risk']  # Target variable

In [46]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [48]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [50]:
models = {
    'Logistic Regression': LogisticRegression(),
    'Decision Tree': DecisionTreeClassifier(),
    'Random Forest': RandomForestClassifier(),
    'SVM': SVC(),
    'KNN': KNeighborsClassifier(),
}


In [52]:
for name, model in models.items():
    model.fit(X_train_scaled, y_train)
    y_pred = model.predict(X_test_scaled)
    print(f"{name} Accuracy: {accuracy_score(y_test, y_pred)}")
    print(f"Classification Report for {name}:\n", classification_report(y_test, y_pred))
    print(f"Confusion Matrix for {name}:\n", confusion_matrix(y_test, y_pred))
    print("\n" + "="*60 + "\n")


E:\Anaconda\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Logistic Regression Accuracy: 0.93
Classification Report for Logistic Regression:
               precision    recall  f1-score   support

           0       0.96      0.97      0.96       139
           1       1.00      1.00      1.00         1
           2       0.89      0.96      0.93        26
           3       0.83      0.74      0.78        34

    accuracy                           0.93       200
   macro avg       0.92      0.92      0.92       200
weighted avg       0.93      0.93      0.93       200

Confusion Matrix for Logistic Regression:
 [[135   0   0   4]
 [  0   1   0   0]
 [  0   0  25   1]
 [  6   0   3  25]]


Decision Tree Accuracy: 0.94
Classification Report for Decision Tree:
               precision    recall  f1-score   support

           0       0.99      0.99      0.99       139
           1       1.00      1.00      1.00         1
           2       0.90      0.73      0.81        26
           3       0.79      0.91      0.85        34

    accuracy     

In [54]:
param_grid = {
    'n_estimators': [100, 200],
    'max_depth': [10, 20, None],
    'min_samples_split': [2, 5],
}

grid_search_rf = GridSearchCV(RandomForestClassifier(), param_grid, cv=3, scoring='accuracy')
grid_search_rf.fit(X_train_scaled, y_train)

print(f"Best Random Forest Parameters: {grid_search_rf.best_params_}")
best_rf = grid_search_rf.best_estimator_

# Evaluate the tuned model
y_pred_rf = best_rf.predict(X_test_scaled)
print(f"Tuned Random Forest Accuracy: {accuracy_score(y_test, y_pred_rf)}")


Best Random Forest Parameters: {'max_depth': None, 'min_samples_split': 2, 'n_estimators': 200}
Tuned Random Forest Accuracy: 0.955


In [56]:
pip install joblib

Note: you may need to restart the kernel to use updated packages.


In [58]:
import joblib
# My best model is best_rf
joblib.dump(best_rf, 'best_model.pkl')

['best_model.pkl']

In [62]:
# Save the encoder
joblib.dump(le, 'label_encoder.pkl')

['label_encoder.pkl']

In [66]:
unique_values = df2['prognosis'].unique()
print(unique_values)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 15 16 17 18 19 14]


In [70]:
# Load the encoder
label_encoder = joblib.load('label_encoder.pkl')

# Get original labels
original_labels = label_encoder.classes_
print(original_labels)

['Allergy' 'Arthritis' 'Asthma' 'Back Pain' 'Catarrh' 'Chickenpox'
 'Common_Cold' 'Dengue' 'Diabetes' 'Gastritis' 'High Blood Pressure'
 'Influenza' 'Insomnia' 'Kidney Stones' 'Lupus' 'Migrain' 'Osteoarthritis'
 'Throat Infection' 'Tonsillitis' 'Urinary Tract Infection']
